language: node_js
node_js:
  - "6"

branches:
  only:
    - master

before_install:
  - pip install --user codecov

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  npm run build

sudo: false

after_success:
  npm test

cache:
  directories:
    - node_modules

notifications:
    email: false
