"use strict";
exports.__esModule = true;
var classes_1 = require("./classes");
var extend = new classes_1.ClassExtend();
var mix = new classes_1.ClassMix();
var optionsMix = new classes_1.ClassOptionsMix();
var optionsExtend = new classes_1.ClassOptionsExtend();
var l = function () {
    var args = [];
    for (var _i = 0; _i < arguments.length; _i++) {
        args[_i] = arguments[_i];
    }
    return false;
};
l(classes_1.ClassExtend.parProp);
l(classes_1.ClassExtend.prop);
l(classes_1.ClassExtend._mixins_);
l(classes_1.ClassExtend.prop1);
l(classes_1.ClassExtend.prop2);
l(extend.parMethod());
l(extend.method());
l(extend.method1());
l(extend.method2());
l(extend.mixin1Prop);
l(extend.mixin2Prop);
l(extend.childProp);
l(extend.parentProp);
l(classes_1.ClassMix.prop);
l(classes_1.ClassMix._mixins_);
l(classes_1.ClassMix.prop1);
l(classes_1.ClassMix.prop2);
l(mix.method());
l(mix.method1());
l(mix.method2());
l(mix.mixin1Prop);
l(mix.mixin2Prop);
l(mix.childProp);
l(classes_1.ClassOptionsExtend.parProp);
l(classes_1.ClassOptionsExtend.prop);
l(classes_1.ClassOptionsExtend._mixins_);
l(classes_1.ClassOptionsExtend.prop1);
l(classes_1.ClassOptionsExtend.prop2);
l(optionsExtend.parMethod());
l(optionsExtend.method());
l(optionsExtend.method1());
l(optionsExtend.method2());
l(optionsExtend.mixin1Prop);
l(optionsExtend.mixin2Prop);
l(optionsExtend.childProp);
l(optionsExtend.parentProp);
l(classes_1.ClassOptionsMix.prop);
l(classes_1.ClassOptionsMix._mixins_);
l(classes_1.ClassOptionsMix.prop1);
l(classes_1.ClassOptionsMix.prop2);
l(optionsMix.method());
l(optionsMix.method1());
l(optionsMix.method2());
l(optionsMix.mixin1Prop);
l(optionsMix.mixin2Prop);
l(optionsMix.childProp);
